### ISSUE TITLE
Certain valid characters for syntax are being escaped in note content resulting in odd looking output

### ISSUE THREAD

**Issue by Phl3bas** [Maxamuss/code-atlas#17]
First of all, really nice app, i noticed when i was testing in out that it escapes centain characters in the body of the notes, specifically in my case the value ">" gets rendered on the page as "&gt;" i think this can be fixed either by turning off autoescaping it in the template with something like

`{{ context_var|safe }}
{% autoescape off %}
    {{ context_var }}
{% endautoescape %}`

or in the view using djangos unescape_entities function in django.utils.text

i would test this myself and make a PR but im currently supposed to be working and not looking at your cool app ;) so ill leave this here.

example of the page not escaping can be seen on my note below

![codeatlas](https://user-images.githubusercontent.com/45594209/82316882-60cee400-99c5-11ea-831b-e7d2a1d90b85.png)

**Comment by Maxamuss** [comment]
Thanks! Seems to be marked.js causing some issues. Fixed for code blocks. Cheers for pointing out the issue
